repos:
- repo: https://github.com/asottile/reorder_python_imports
  rev: v2.4.0
  hooks:
    - id: reorder-python-imports
      name: Reorder Python imports (lk_utils, tests)
      args: ['--application-directories', 'tests:utils:lk_utils']
- repo: https://github.com/pycqa/flake8
  rev: 3.7.7
  hooks:
    - id: flake8
      args: ['--ignore=F401,E402,W', '--max-line-length=120', '--show-source']
      additional_dependencies: [flake8-bugbear]
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.0.1
  hooks:
    - id: trailing-whitespace
    - id: end-of-file-fixer
    - id: debug-statements
    - id: check-merge-conflict
    - id: fix-byte-order-marker
    - id: double-quote-string-fixer
    - id: fix-encoding-pragma
